# Usa la imagen oficial de Node.js 22
FROM node:22

# Define el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia los archivos del proyecto Angular al contenedor
COPY frontend/ .

# Instalar dependencias
RUN npm install

# Exponer el puerto 4200
EXPOSE 4200

# Iniciar el servidor Angular en 0.0.0.0
CMD ["npm", "run", "start", "--", "--host", "0.0.0.0"]
