FROM node:22

WORKDIR /app

# Instalamos Angular CLI global
RUN npm install -g @angular/cli

# CMD que instala dependencias y arranca el server
CMD ["sh", "-c", "npm install && npm run start -- --host 0.0.0.0"]
