version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tfg_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - tfg_network

  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile-backend
    container_name: backend-container
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/tfg_db?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    volumes:
      - ../backend:/app
      - ~/.m2:/root/.m2
    networks:
      - tfg_network

  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile-frontend
    container_name: frontend-container
    restart: always
    ports:
      - "4200:4200"
    volumes:
      - ../frontend:/app
    depends_on:
      - backend
    networks:
      - tfg_network


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql
    networks:
      - tfg_network

volumes:
  mysql_data:


networks:
  tfg_network:
